name: Backend system tests

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"

jobs:
  system-tests:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        working-directory: ./backend
        run: npm install
      - name: Run Server and Test with Newman
        working-directory: ./backend
        run: npm run test:system
